package com.securevault.ui.screens

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.*
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel

@OptIn(ExperimentalMaterial3Api::class, ExperimentalLayoutApi::class)
@Composable
fun EntryEditScreen(entryId: Long?, onBack: () -> Unit, vm: EntryViewModel = hiltViewModel()) {
    val ctx = LocalContext.current
    val existing by vm.entry.collectAsState()
    val saved by vm.saved.collectAsState()
    val hintGenerated by vm.hintGeneratedPwd.collectAsState()

    var title by remember { mutableStateOf("") }
    var profile by remember { mutableStateOf("Личное") }
    var cat by remember { mutableStateOf("Общее") }
    var user by remember { mutableStateOf("") }
    var pwd by remember { mutableStateOf("") }
    var url by remember { mutableStateOf("") }
    var notes by remember { mutableStateOf("") }
    var hintText by remember { mutableStateOf("") }
    var hintKeywords by remember { mutableStateOf("") }
    var extraSeed by remember { mutableStateOf("") }
    var changeInterval by remember { mutableIntStateOf(0) }
    var fav by remember { mutableStateOf(false) }
    var showPwd by remember { mutableStateOf(false) }
    var showRandomGen by remember { mutableStateOf(false) }
    var showHintGen by remember { mutableStateOf(false) }
    var genLen by remember { mutableFloatStateOf(20f) }
    var genUpper by remember { mutableStateOf(true) }
    var genDigits by remember { mutableStateOf(true) }
    var genSymbols by remember { mutableStateOf(true) }

    val profiles = listOf("Личное", "Рабочее", "Другое")
    val cats = listOf("Общее", "Соцсети", "Банки", "Работа", "Почта", "Другое")
    val intervals = listOf(
        0 to "Без напоминания", 30 to "30 дней", 60 to "60 дней",
        90 to "90 дней", 180 to "180 дней", 365 to "1 год"
    )

    LaunchedEffect(entryId) { entryId?.let { vm.load(it) } }
    LaunchedEffect(existing) {
        existing?.let { e ->
            title = e.title; profile = e.profile; cat = e.category
            user = e.username; pwd = e.password; url = e.url; notes = e.notes
            hintText = e.hintText; hintKeywords = e.hintKeywords
            changeInterval = e.changeIntervalDays; fav = e.isFavorite
            genLen = e.genLength.toFloat(); genUpper = e.genUpper
            genDigits = e.genDigits; genSymbols = e.genSymbols
        }
    }
    LaunchedEffect(saved) { if (saved) onBack() }

    fun copy(text: String) = (ctx.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager)
        .setPrimaryClip(ClipData.newPlainText("sv", text))

    // ─── Диалог: случайный генератор ────────────────────────────────────────
    if (showRandomGen) {
        var preview by remember {
            mutableStateOf(vm.generateRandom(genLen.toInt(), genUpper, genDigits, genSymbols))
        }
        AlertDialog(onDismissRequest = { showRandomGen = false },
            title = { Text("Случайный пароль") },
            text = {
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    Surface(color = MaterialTheme.colorScheme.surfaceVariant, shape = MaterialTheme.shapes.small) {
                        Row(Modifier.padding(12.dp), verticalAlignment = Alignment.CenterVertically) {
                            Text(preview, Modifier.weight(1f), fontSize = 13.sp, fontWeight = FontWeight.Medium)
                            IconButton({
                                preview = vm.generateRandom(genLen.toInt(), genUpper, genDigits, genSymbols)
                            }) { Icon(Icons.Default.Refresh, null) }
                        }
                    }
                    Text("Длина: ${genLen.toInt()}", fontSize = 13.sp)
                    Slider(genLen, { v ->
                        genLen = v; preview = vm.generateRandom(v.toInt(), genUpper, genDigits, genSymbols)
                    }, valueRange = 8f..40f, steps = 31)
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Checkbox(genUpper, { genUpper = it; preview = vm.generateRandom(genLen.toInt(), it, genDigits, genSymbols) })
                        Text("Заглавные (A-Z)")
                    }
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Checkbox(genDigits, { genDigits = it; preview = vm.generateRandom(genLen.toInt(), genUpper, it, genSymbols) })
                        Text("Цифры (0-9)")
                    }
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Checkbox(genSymbols, { genSymbols = it; preview = vm.generateRandom(genLen.toInt(), genUpper, genDigits, it) })
                        Text("Символы (!@#...)")
                    }
                }
            },
            confirmButton = {
                Button({ pwd = preview; vm.clearHintFlag(); showRandomGen = false }) { Text("Использовать") }
            },
            dismissButton = { TextButton({ showRandomGen = false }) { Text("Отмена") } }
        )
    }

    // ─── Диалог: генератор ИЗ ПОДСКАЗОК ────────────────────────────────────
    if (showHintGen) {
        var localKw by remember { mutableStateOf(hintKeywords) }
        var localSeed by remember { mutableStateOf(extraSeed) }
        var localLen by remember { mutableFloatStateOf(genLen) }
        var localUpper by remember { mutableStateOf(genUpper) }
        var localDigits by remember { mutableStateOf(genDigits) }
        var localSymbols by remember { mutableStateOf(genSymbols) }

        fun regen() = if (localKw.isNotBlank())
            HintPasswordGenerator.generate(localKw, localSeed, localLen.toInt(), localUpper, localDigits, localSymbols)
        else ""

        var generatedPwd by remember { mutableStateOf(regen()) }

        AlertDialog(
            onDismissRequest = { showHintGen = false },
            title = {
                Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    Icon(Icons.Default.Psychology, null, tint = MaterialTheme.colorScheme.secondary)
                    Text("Пароль из подсказок")
                }
            },
            text = {
                Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {

                    // Объяснение
                    Surface(color = MaterialTheme.colorScheme.secondaryContainer.copy(alpha = 0.5f),
                        shape = MaterialTheme.shapes.small) {
                        Text(
                            "Одни и те же слова → всегда один и тот же пароль.\n" +
                            "Забыли пароль? Просто вспомните слова — он восстановится.",
                            fontSize = 12.sp, color = MaterialTheme.colorScheme.secondary,
                            modifier = Modifier.padding(10.dp)
                        )
                    }

                    OutlinedTextField(
                        value = localKw,
                        onValueChange = { localKw = it; generatedPwd = regen() },
                        label = { Text("Ключевые слова") },
                        placeholder = { Text("кот, дом, 1999, синий ...") },
                        leadingIcon = { Icon(Icons.Default.Psychology, null) },
                        modifier = Modifier.fillMaxWidth(), singleLine = true
                    )

                    OutlinedTextField(
                        value = localSeed,
                        onValueChange = { localSeed = it; generatedPwd = regen() },
                        label = { Text("Секрет (необязательно)") },
                        placeholder = { Text("Число или буквы только в вашей голове") },
                        leadingIcon = { Icon(Icons.Default.VpnKey, null) },
                        modifier = Modifier.fillMaxWidth(), singleLine = true
                    )

                    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                        Text("Длина: ${localLen.toInt()}", fontSize = 12.sp,
                            modifier = Modifier.align(Alignment.CenterVertically))
                        Slider(localLen, { v -> localLen = v; generatedPwd = regen() },
                            Modifier.weight(1f), valueRange = 8f..40f)
                    }

                    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceEvenly) {
                        FilterChip(localUpper, { localUpper = !localUpper; generatedPwd = regen() }, label = { Text("A-Z") })
                        FilterChip(localDigits, { localDigits = !localDigits; generatedPwd = regen() }, label = { Text("0-9") })
                        FilterChip(localSymbols, { localSymbols = !localSymbols; generatedPwd = regen() }, label = { Text("!@#") })
                    }

                    // Эмодзи предпросмотр
                    val emoji = HintVisualizer.toEmojis(localKw)
                    if (emoji.isNotEmpty()) {
                        Surface(color = MaterialTheme.colorScheme.surfaceVariant, shape = MaterialTheme.shapes.medium) {
                            Column(Modifier.fillMaxWidth().padding(10.dp), horizontalAlignment = Alignment.CenterHorizontally) {
                                Text("Визуальная подсказка:", fontSize = 11.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)
                                Text(emoji, fontSize = 28.sp)
                            }
                        }
                    }

                    // Результат
                    if (generatedPwd.isNotEmpty()) {
                        Surface(color = MaterialTheme.colorScheme.secondaryContainer,
                            shape = MaterialTheme.shapes.medium, modifier = Modifier.fillMaxWidth()) {
                            Column(Modifier.padding(12.dp), horizontalAlignment = Alignment.CenterHorizontally) {
                                Text("Сгенерированный пароль:", fontSize = 11.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)
                                Spacer(Modifier.height(4.dp))
                                Text(generatedPwd, fontWeight = FontWeight.Bold, fontSize = 14.sp,
                                    textAlign = TextAlign.Center,
                                    color = MaterialTheme.colorScheme.onSecondaryContainer)
                                Spacer(Modifier.height(8.dp))
                                OutlinedButton({ copy(generatedPwd) }, Modifier.fillMaxWidth()) {
                                    Icon(Icons.Default.ContentCopy, null, Modifier.size(16.dp))
                                    Spacer(Modifier.width(4.dp))
                                    Text("Копировать", fontSize = 12.sp)
                                }
                            }
                        }
                    } else {
                        Text("Введите ключевые слова выше.", fontSize = 13.sp,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            textAlign = TextAlign.Center, modifier = Modifier.fillMaxWidth())
                    }
                }
            },
            confirmButton = {
                Button(
                    onClick = {
                        pwd = generatedPwd
                        hintKeywords = localKw; extraSeed = localSeed
                        genLen = localLen; genUpper = localUpper
                        genDigits = localDigits; genSymbols = localSymbols
                        vm.generateFromHints(localKw, localSeed, localLen.toInt(), localUpper, localDigits, localSymbols)
                        showHintGen = false
                    },
                    enabled = generatedPwd.isNotEmpty()
                ) { Text("Использовать как пароль") }
            },
            dismissButton = { TextButton({ showHintGen = false }) { Text("Отмена") } }
        )
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(if (entryId == null) "Новая запись" else "Редактировать") },
                navigationIcon = { IconButton(onBack) { Icon(Icons.Default.ArrowBack, null) } },
                actions = {
                    IconButton({ fav = !fav }) {
                        Icon(if (fav) Icons.Default.Star else Icons.Default.StarBorder, null,
                            tint = if (fav) MaterialTheme.colorScheme.secondary else MaterialTheme.colorScheme.onSurface)
                    }
                    IconButton({
                        vm.save(entryId ?: 0, title, profile, cat, user, pwd, url, notes,
                            hintText, hintKeywords, changeInterval, fav,
                            genLen.toInt(), genUpper, genDigits, genSymbols)
                    }) { Icon(Icons.Default.Check, "Сохранить") }
                }
            )
        }
    ) { pad ->
        Column(Modifier.fillMaxSize().padding(pad).verticalScroll(rememberScrollState()).padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)) {

            OutlinedTextField(value = title, onValueChange = { title = it }, label = { Text("Название *") },
                modifier = Modifier.fillMaxWidth(), leadingIcon = { Icon(Icons.Default.Label, null) }, singleLine = true)

            var profExp by remember { mutableStateOf(false) }
            ExposedDropdownMenuBox(profExp, { profExp = it }) {
                OutlinedTextField(value = profile, onValueChange = {}, readOnly = true, label = { Text("Профиль") },
                    leadingIcon = { Icon(if (profile == "Рабочее") Icons.Default.Work else Icons.Default.Person, null) },
                    trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(profExp) },
                    modifier = Modifier.fillMaxWidth().menuAnchor())
                ExposedDropdownMenu(profExp, { profExp = false }) {
                    profiles.forEach { p -> DropdownMenuItem(text = { Text(p) }, onClick = { profile = p; profExp = false }) }
                }
            }

            var catExp by remember { mutableStateOf(false) }
            ExposedDropdownMenuBox(catExp, { catExp = it }) {
                OutlinedTextField(value = cat, onValueChange = {}, readOnly = true, label = { Text("Категория") },
                    trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(catExp) },
                    modifier = Modifier.fillMaxWidth().menuAnchor())
                ExposedDropdownMenu(catExp, { catExp = false }) {
                    cats.forEach { c -> DropdownMenuItem(text = { Text(c) }, onClick = { cat = c; catExp = false }) }
                }
            }

            OutlinedTextField(value = user, onValueChange = { user = it }, label = { Text("Логин / Email") },
                modifier = Modifier.fillMaxWidth(), leadingIcon = { Icon(Icons.Default.Person, null) },
                trailingIcon = { if (user.isNotEmpty()) IconButton({ copy(user) }) {
                    Icon(Icons.Default.ContentCopy, null, Modifier.size(18.dp)) } },
                singleLine = true)

            // ── Пароль ──
            OutlinedTextField(
                value = pwd, onValueChange = { pwd = it; vm.clearHintFlag() },
                label = { Text(if (hintGenerated) "Пароль (из подсказок ✓)" else "Пароль *") },
                visualTransformation = if (showPwd) VisualTransformation.None else PasswordVisualTransformation(),
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password),
                modifier = Modifier.fillMaxWidth().then(
                    if (hintGenerated) Modifier.border(1.dp, MaterialTheme.colorScheme.secondary, MaterialTheme.shapes.small)
                    else Modifier
                ),
                leadingIcon = {
                    Icon(if (hintGenerated) Icons.Default.Psychology else Icons.Default.Lock, null,
                        tint = if (hintGenerated) MaterialTheme.colorScheme.secondary
                               else MaterialTheme.colorScheme.onSurfaceVariant)
                },
                trailingIcon = {
                    Row {
                        if (pwd.isNotEmpty()) IconButton({ copy(pwd) }) {
                            Icon(Icons.Default.ContentCopy, null, Modifier.size(18.dp))
                        }
                        IconButton({ showPwd = !showPwd }) {
                            Icon(if (showPwd) Icons.Default.VisibilityOff else Icons.Default.Visibility, null)
                        }
                        IconButton({ showRandomGen = true }) {
                            Icon(Icons.Default.Casino, "Случайный пароль")
                        }
                    }
                }, singleLine = true
            )

            // ── ГЛАВНАЯ КНОПКА: Сгенерировать из подсказок ──
            Button(
                onClick = { showHintGen = true },
                modifier = Modifier.fillMaxWidth(),
                colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.secondaryContainer,
                    contentColor = MaterialTheme.colorScheme.onSecondaryContainer)
            ) {
                Icon(Icons.Default.Psychology, null)
                Spacer(Modifier.width(8.dp))
                Column(horizontalAlignment = Alignment.Start) {
                    Text("Сгенерировать пароль из подсказок", fontSize = 14.sp, fontWeight = FontWeight.Medium)
                    Text("Те же слова → тот же пароль, всегда",
                        fontSize = 11.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
            }

            OutlinedTextField(value = url, onValueChange = { url = it }, label = { Text("URL (необязательно)") },
                modifier = Modifier.fillMaxWidth(), leadingIcon = { Icon(Icons.Default.Language, null) }, singleLine = true)

            OutlinedTextField(value = notes, onValueChange = { notes = it }, label = { Text("Заметки") },
                modifier = Modifier.fillMaxWidth(), minLines = 2, maxLines = 4)

            // ── Планировщик ──
            HorizontalDivider()
            Text("Напоминание о смене", fontWeight = FontWeight.Medium, fontSize = 14.sp)
            var intExp by remember { mutableStateOf(false) }
            val intervalLabel = intervals.find { it.first == changeInterval }?.second ?: "Без напоминания"
            ExposedDropdownMenuBox(intExp, { intExp = it }) {
                OutlinedTextField(value = intervalLabel, onValueChange = {}, readOnly = true,
                    label = { Text("Менять каждые") },
                    leadingIcon = { Icon(Icons.Default.Schedule, null) },
                    trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(intExp) },
                    modifier = Modifier.fillMaxWidth().menuAnchor())
                ExposedDropdownMenu(intExp, { intExp = false }) {
                    intervals.forEach { (v, l) ->
                        DropdownMenuItem(text = { Text(l) }, onClick = { changeInterval = v; intExp = false })
                    }
                }
            }

            // ── Подсказки ──
            HorizontalDivider()
            Text("Мнемонические подсказки", fontWeight = FontWeight.Medium, fontSize = 14.sp)
            Text("На основе этих слов можно сгенерировать пароль — и восстановить его, если забудете.",
                fontSize = 12.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)

            OutlinedTextField(value = hintText, onValueChange = { hintText = it },
                label = { Text("Текстовая подсказка (только для вас)") },
                placeholder = { Text("«год рождения кошки + номер дома»") },
                leadingIcon = { Icon(Icons.Default.Lightbulb, null) },
                modifier = Modifier.fillMaxWidth(), minLines = 2, maxLines = 3)

            OutlinedTextField(value = hintKeywords, onValueChange = { hintKeywords = it },
                label = { Text("Ключевые слова → пароль") },
                placeholder = { Text("кот, дом, 5, синий ...") },
                leadingIcon = { Icon(Icons.Default.Psychology, null) },
                modifier = Modifier.fillMaxWidth(), singleLine = true)

            // Эмодзи + кнопка генерации
            val emojiPreview = HintVisualizer.toEmojis(hintKeywords)
            if (emojiPreview.isNotEmpty()) {
                Surface(color = MaterialTheme.colorScheme.surfaceVariant, shape = MaterialTheme.shapes.medium) {
                    Column(Modifier.fillMaxWidth().padding(16.dp), horizontalAlignment = Alignment.CenterHorizontally) {
                        Text("Визуальная подсказка:", fontSize = 12.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)
                        Spacer(Modifier.height(8.dp))
                        Text(emojiPreview, fontSize = 36.sp)
                        Spacer(Modifier.height(10.dp))
                        OutlinedButton({ showHintGen = true }, Modifier.fillMaxWidth()) {
                            Icon(Icons.Default.Key, null, Modifier.size(16.dp))
                            Spacer(Modifier.width(6.dp))
                            Text("Создать пароль из этих слов", fontSize = 13.sp)
                        }
                    }
                }
            }

            // Быстрые теги
            Text("Быстрые теги:", fontSize = 12.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)
            FlowRow(horizontalArrangement = Arrangement.spacedBy(6.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
                HintVisualizer.suggestKeywords().forEach { kw ->
                    SuggestionChip(onClick = {
                        hintKeywords = if (hintKeywords.isBlank()) kw
                        else "${hintKeywords.trimEnd(',').trim()}, $kw"
                    }, label = { Text("${HintVisualizer.toEmojis(kw)} $kw", fontSize = 12.sp) })
                }
            }
            Spacer(Modifier.height(32.dp))
        }
    }
}
